insert into classification ( id, description, kind) values ( 'A-A', 'Agriculture, forestry and fishing' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-01', 'Crop and animal production, hunting and related service activities' , 'A', 'A-A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-02', 'Forestry and logging' , 'A', 'A-A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-03', 'Fishing and aquaculture' , 'A', 'A-A');
insert into classification ( id, description, kind) values ( 'A-B', 'Mining and quarrying' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-05', 'Mining of coal and lignite' , 'A', 'A-B');
insert into classification ( id, description, kind, parent_id ) values ( 'A-06', 'Extraction of crude petroleum and natural gas' , 'A', 'A-B');
insert into classification ( id, description, kind, parent_id ) values ( 'A-07', 'Mining of metal ores' , 'A', 'A-B');
insert into classification ( id, description, kind, parent_id ) values ( 'A-08', 'Other mining and quarrying' , 'A', 'A-B');
insert into classification ( id, description, kind, parent_id ) values ( 'A-09', 'Mining support service activities' , 'A', 'A-B');
insert into classification ( id, description, kind) values ( 'A-C', 'Manufacturing' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-10', 'Manufacture of food products' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-11', 'Manufacture of beverages' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-12', 'Manufacture of tobacco products' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-13', 'Manufacture of textiles' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-14', 'Manufacture of wearing apparel' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-15', 'Manufacture of leather and related products' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-16', 'Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-17', 'Manufacture of paper and paper products' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-18', 'Printing and reproduction of recorded media' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-19', 'Manufacture of coke and refined petroleum products' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-20', 'Manufacture of chemicals and chemical products' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-21', 'Manufacture of basic pharmaceutical products and pharmaceutical preparations' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-22', 'Manufacture of rubber and plastics products' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-23', 'Manufacture of other non' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-24', 'Manufacture of basic metals' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-25', 'Manufacture of fabricated metal products, except machinery and equipment' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-26', 'Manufacture of computer, electronic and optical products' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-27', 'Manufacture of electrical equipment' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-28', 'Manufacture of machinery and equipment n.e.c.' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-29', 'Manufacture of motor vehicles, trailers and semi' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-30', 'Manufacture of other transport equipment' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-31', 'Manufacture of furniture' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-32', 'Other manufacturing' , 'A', 'A-C');
insert into classification ( id, description, kind, parent_id ) values ( 'A-33', 'Repair and installation of machinery and equipment' , 'A', 'A-C');
insert into classification ( id, description, kind) values ( 'A-D', 'Electricity, gas, steam and air conditioning supply' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-35', 'Electricity, gas, steam and air conditioning supply' , 'A', 'A-D');
insert into classification ( id, description, kind) values ( 'A-E', 'Water supply; sewerage, waste management and remediation activities' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-36', 'Water collection, treatment and supply' , 'A', 'A-E');
insert into classification ( id, description, kind, parent_id ) values ( 'A-37', 'Sewerage' , 'A', 'A-E');
insert into classification ( id, description, kind, parent_id ) values ( 'A-38', 'Waste collection, treatment and disposal activities; materials recovery' , 'A', 'A-E');
insert into classification ( id, description, kind, parent_id ) values ( 'A-39', 'Remediation activities and other waste management services' , 'A', 'A-E');
insert into classification ( id, description, kind) values ( 'A-F', 'Construction' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-41', 'Construction of buildings' , 'A', 'A-F');
insert into classification ( id, description, kind, parent_id ) values ( 'A-42', 'Civil engineering' , 'A', 'A-F');
insert into classification ( id, description, kind, parent_id ) values ( 'A-43', 'Specialized construction activities' , 'A', 'A-F');
insert into classification ( id, description, kind) values ( 'A-G', 'Wholesale and retail trade; repair of motor vehicles and motorcycles' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-45', 'Wholesale and retail trade and repair of motor vehicles and motorcycles' , 'A', 'A-G');
insert into classification ( id, description, kind, parent_id ) values ( 'A-46', 'Wholesale trade, except of motor vehicles and motorcycles' , 'A', 'A-G');
insert into classification ( id, description, kind, parent_id ) values ( 'A-47', 'Retail trade, except of motor vehicles and motorcycles' , 'A', 'A-G');
insert into classification ( id, description, kind) values ( 'A-H', 'Transportation and storage' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-49', 'Land transport and transport via pipelines' , 'A', 'A-H');
insert into classification ( id, description, kind, parent_id ) values ( 'A-50', 'Water transport' , 'A', 'A-H');
insert into classification ( id, description, kind, parent_id ) values ( 'A-51', 'Air transport' , 'A', 'A-H');
insert into classification ( id, description, kind, parent_id ) values ( 'A-52', 'Warehousing and support activities for transportation' , 'A', 'A-H');
insert into classification ( id, description, kind, parent_id ) values ( 'A-53', 'Postal and courier activities' , 'A', 'A-H');
insert into classification ( id, description, kind) values ( 'A-I', 'Accommodation and food service activities' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-55', 'Accommodation' , 'A', 'A-I');
insert into classification ( id, description, kind, parent_id ) values ( 'A-56', 'Food and beverage service activities' , 'A', 'A-I');
insert into classification ( id, description, kind) values ( 'A-J', 'Information and communication' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-58', 'Publishing activities' , 'A', 'A-J');
insert into classification ( id, description, kind, parent_id ) values ( 'A-59', 'Motion picture, video and television programme production, sound recording and music publishing activities' , 'A', 'A-J');
insert into classification ( id, description, kind, parent_id ) values ( 'A-60', 'Programming and broadcasting activities' , 'A', 'A-J');
insert into classification ( id, description, kind, parent_id ) values ( 'A-61', 'Telecommunications' , 'A', 'A-J');
insert into classification ( id, description, kind, parent_id ) values ( 'A-62', 'Computer programming, consultancy and related activities' , 'A', 'A-J');
insert into classification ( id, description, kind, parent_id ) values ( 'A-63', 'Information service activities' , 'A', 'A-J');
insert into classification ( id, description, kind) values ( 'A-K', 'Financial and insurance activities' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-64', 'Financial service activities, except insurance and pension funding' , 'A', 'A-K');
insert into classification ( id, description, kind, parent_id ) values ( 'A-65', 'Insurance, reinsurance and pension funding, except compulsory social security' , 'A', 'A-K');
insert into classification ( id, description, kind, parent_id ) values ( 'A-66', 'Activities auxiliary to financial service and insurance activities' , 'A', 'A-K');
insert into classification ( id, description, kind) values ( 'A-L', 'Real estate activities' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-68', 'Real estate activities' , 'A', 'A-L');
insert into classification ( id, description, kind) values ( 'A-M', 'Professional, scientific and technical activities' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-69', 'Legal and accounting activities' , 'A', 'A-M');
insert into classification ( id, description, kind, parent_id ) values ( 'A-70', 'Activities of head offices; management consultancy activities' , 'A', 'A-M');
insert into classification ( id, description, kind, parent_id ) values ( 'A-71', 'Architectural and engineering activities; technical testing and analysis' , 'A', 'A-M');
insert into classification ( id, description, kind, parent_id ) values ( 'A-72', 'Scientific research and development' , 'A', 'A-M');
insert into classification ( id, description, kind, parent_id ) values ( 'A-73', 'Advertising and market research' , 'A', 'A-M');
insert into classification ( id, description, kind, parent_id ) values ( 'A-74', 'Other professional, scientific and technical activities' , 'A', 'A-M');
insert into classification ( id, description, kind, parent_id ) values ( 'A-75', 'Veterinary activities' , 'A', 'A-M');
insert into classification ( id, description, kind) values ( 'A-N', 'Administrative and support service activities' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-77', 'Rental and leasing activities' , 'A', 'A-N');
insert into classification ( id, description, kind, parent_id ) values ( 'A-78', 'Employment activities' , 'A', 'A-N');
insert into classification ( id, description, kind, parent_id ) values ( 'A-79', 'Travel agency, tour operator, reservation service and related activities' , 'A', 'A-N');
insert into classification ( id, description, kind, parent_id ) values ( 'A-80', 'Security and investigation activities' , 'A', 'A-N');
insert into classification ( id, description, kind, parent_id ) values ( 'A-81', 'Services to buildings and landscape activities' , 'A', 'A-N');
insert into classification ( id, description, kind, parent_id ) values ( 'A-82', 'Office administrative, office support and other business support activities' , 'A', 'A-N');
insert into classification ( id, description, kind) values ( 'A-O', 'Public administration and defence; compulsory social security' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-84', 'Public administration and defence; compulsory social security' , 'A', 'A-O');
insert into classification ( id, description, kind) values ( 'A-P', 'Education' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-85', 'Education' , 'A', 'A-P');
insert into classification ( id, description, kind) values ( 'A-Q', 'Human health and social work activities' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-86', 'Human health activities' , 'A', 'A-Q');
insert into classification ( id, description, kind, parent_id ) values ( 'A-87', 'Residential care activities' , 'A', 'A-Q');
insert into classification ( id, description, kind, parent_id ) values ( 'A-88', 'Social work activities without accommodation' , 'A', 'A-Q');
insert into classification ( id, description, kind) values ( 'A-R', 'Arts, entertainment and recreation' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-90', 'Creative, arts and entertainment activities' , 'A', 'A-R');
insert into classification ( id, description, kind, parent_id ) values ( 'A-91', 'Libraries, archives, museums and other cultural activities' , 'A', 'A-R');
insert into classification ( id, description, kind, parent_id ) values ( 'A-92', 'Gambling and betting activities' , 'A', 'A-R');
insert into classification ( id, description, kind, parent_id ) values ( 'A-93', 'Sports activities and amusement and recreation activities' , 'A', 'A-R');
insert into classification ( id, description, kind) values ( 'A-S', 'Other service activities' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-94', 'Activities of membership organizations' , 'A', 'A-S');
insert into classification ( id, description, kind, parent_id ) values ( 'A-95', 'Repair of computers and personal and household goods' , 'A', 'A-S');
insert into classification ( id, description, kind, parent_id ) values ( 'A-96', 'Other personal service activities' , 'A', 'A-S');
insert into classification ( id, description, kind) values ( 'A-T', 'Activities of households as employers; undifferentiated goods' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-97', 'Activities of households as employers of domestic personnel' , 'A', 'A-T');
insert into classification ( id, description, kind, parent_id ) values ( 'A-98', 'Undifferentiated goods' , 'A', 'A-T');
insert into classification ( id, description, kind) values ( 'A-U', 'Activities of extraterritorial organizations and bodies' , 'A');
insert into classification ( id, description, kind, parent_id ) values ( 'A-99', 'Activities of extraterritorial organizations and bodies' , 'A', 'A-U');
