DROP TABLE PUBLIC.OPPORTUNITY_INDEX  IF EXISTS
CREATE MEMORY TABLE PUBLIC.OPPORTUNITY_INDEX(ID BIGINT NOT NULL,OPPORTUNITY_ID BIGINT NOT NULL,GEO_COORDINATATES VARCHAR(100),SEARCH_VECTOR VARCHAR(10000),CONSTRAINT DONTLETMEGETME4711 FOREIGN KEY(OPPORTUNITY_ID) REFERENCES PUBLIC.OPPORTUNITY(ID))
