DROP TABLE PUBLIC.OPPORTUNITY_GIS_INDEX  IF EXISTS
DROP TABLE PUBLIC.OPPORTUNITY_TS_INDEX  IF EXISTS
CREATE MEMORY TABLE PUBLIC.OPPORTUNITY_GIS_INDEX(ID VARCHAR(50) NOT NULL PRIMARY KEY,OPPORTUNITY_ID BIGINT NOT NULL,GEO_COORDINATES VARCHAR(25),ADDRESS_ID BIGINT NOT NULL,CONSTRAINT DONTLENTMEGETME01 FOREIGN KEY(OPPORTUNITY_ID) REFERENCES PUBLIC.OPPORTUNITY(ID),CONSTRAINT DONTLENTMEGETME02 FOREIGN KEY(ADDRESS_ID) REFERENCES PUBLIC.ADDRESS(ID))
CREATE MEMORY TABLE PUBLIC.OPPORTUNITY_TS_INDEX(ID VARCHAR(50) NOT NULL PRIMARY KEY,OPPORTUNITY_ID BIGINT NOT NULL,SEARCH_VECTOR VARCHAR(25),CONSTRAINT DONTLENTMEGETME03 FOREIGN KEY(OPPORTUNITY_ID) REFERENCES PUBLIC.OPPORTUNITY(ID))
