DROP TABLE PUBLIC.OPPORTUNITY_GIS_INDEX  IF EXISTS
DROP TABLE PUBLIC.OPPORTUNITY_TS_INDEX  IF EXISTS
CREATE MEMORY TABLE PUBLIC.OPPORTUNITY_GIS_INDEX(ID BIGINT NOT NULL PRIMARY KEY,OPPORTUNITY_ID BIGINT NOT NULL,GEO_COORDINATES VARCHAR(255),CONSTRAINT DONTLETMEGETME01 FOREIGN KEY(OPPORTUNITY_ID) REFERENCES PUBLIC.OPPORTUNITY(ID))
CREATE MEMORY TABLE PUBLIC.OPPORTUNITY_TS_INDEX(ID BIGINT NOT NULL PRIMARY KEY,OPPORTUNITY_ID BIGINT NOT NULL,SEARCH_VECTOR VARCHAR(255),CONSTRAINT DONTLETMEGETME02 FOREIGN KEY(OPPORTUNITY_ID) REFERENCES PUBLIC.OPPORTUNITY(ID))